name: CI
on: [push]
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build charts
      shell: bash
      run: |
        wget --no-verbose "https://get.helm.sh/helm-v3.2.0-linux-amd64.tar.gz"
        tar -zxf "helm-v3.2.0-linux-amd64.tar.gz"
        chmod +x linux-amd64/helm

        ./linux-amd64/helm version
        mkdir /tmp/charts

        for dir in charts/*; do ./linux-amd64/helm package -d /tmp/charts "${dir}"; done

        ./linux-amd64/helm repo index /tmp/charts
    - name: Checkout gh-pages
      if: github.ref == 'refs/heads/master'
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Push gh-pages
      if: github.ref == 'refs/heads/master'
      shell: bash
      run: |
        git config --global user.name 'Korviakov Andrey'
        git config --global user.email '4lifenet@gmail.com'

        mv /tmp/charts/* .

        git add $(git ls-files -o --exclude-standard *.tgz)
        git add index.yaml
        git status
        git commit -m 'Update Helm Repo'
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/shurshun/test-repo.git gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.gh_access_token }}
